name: Buzz Recipe Importer

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # every hour

permissions:
  contents: read

env:
  CHANNEL_ID: ${{ vars.CHANNEL_ID }}

jobs:
  create-index:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt
      - run: python app.py $CHANNEL_ID
        env:
          DEVELOPER_KEY: ${{ secrets.GOOGLE_API_DEVELOPER_KEY }}
          ALGOLIA_APPLICATOIN_ID: ${{ secrets.ALGOLIA_APPLICATOIN_ID }}
          ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
