name: Buzz Recipe Importer

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # every hour

permissions:
  contents: read

env:
  CHANNEL_ID: ${{ vars.CHANNEL_ID }}

jobs:
  create-index:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run: python app.py $CHANNEL_ID
        env:
          DEVELOPER_KEY: ${{ secrets.GOOGLE_API_DEVELOPER_KEY }}
          ALGOLIA_APPLICATOIN_ID: ${{ secrets.ALGOLIA_APPLICATOIN_ID }}
          ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
